export type PlayMode =
  | "direct"
  | "match"
  | "symbol"
  | "combo"
  | "triple"
  | "pairs"
  | "compare"
  | "add"
  | "grid"
  | "path";

export type PlayFamily =
  | "金额即中"
  | "数字对比"
  | "找图符"
  | "三同图"
  | "比大小"
  | "数字相加"
  | "九宫格"
  | "走步"
  | "两同图"
  | "组合玩法";

export type PrizeTier = {
  amount: number;
  weight: number;
};

export type TicketDistribution = {
  targetReturn: number;
  smallWinsPerBook: [number, number];
  hundredEveryBooks: number;
  jackpotEveryBooks: number;
  note: string;
};

export type SymbolRule = {
  label: string;
  multiplier: number;
  award?: "amount" | "all";
};

export type OfficialPrizeGroup = {
  groupSize: number;
  prizeCounts: Array<{
    amount: number;
    count: number;
  }>;
  sourceUrl: string;
};

export type TicketType = {
  id: string;
  name: string;
  subtitle: string;
  issuer: "中国福利彩票" | "中国体育彩票";
  price: number;
  bookSize: number;
  opportunities: number;
  opportunityLabel?: string;
  prizeTierCount: number;
  topPrize: number;
  mode: PlayMode;
  playFamily: PlayFamily;
  mechanic: string;
  design: string;
  color: string;
  ink: string;
  accent: string;
  artSymbols: string[];
  variantCount: number;
  prizeTiers: PrizeTier[];
  distribution: TicketDistribution;
  evidence: "官方详规" | "官方介绍" | "官方目录";
  sourceUrl: string;
  publishedWinRate?: number;
  winningNumberCount?: number;
  winningSymbols?: SymbolRule[];
  matchMultipliers?: Array<{ label: string; multiplier: number }>;
  pairRule?: {
    matchLabel: string;
    bonusLabel: string;
    bonusMultiplier: number;
  };
  officialPrizeGroup?: OfficialPrizeGroup;
};

type TicketSeed = Omit<
  TicketType,
  "bookSize" | "prizeTiers" | "distribution" | "artSymbols" | "variantCount"
> & {
  bookSize?: number;
  artSymbols?: string[];
  variantCount?: number;
  distribution?: Partial<TicketDistribution>;
};

const OFFICIAL_CATALOG = "https://www.qlfc.com.cn/guaguale/";
const HORSE_2026_RULES =
  "https://www.gdlottery.cn/html/gonggao/20251225/93409.html";

const HORSE_2026_PRIZE_GROUPS = {
  "wu-horse": {
    groupSize: 1_800_000,
    prizeCounts: [
      { amount: 100_000, count: 1 },
      { amount: 10_000, count: 5 },
      { amount: 1_000, count: 50 },
      { amount: 500, count: 100 },
      { amount: 200, count: 500 },
      { amount: 100, count: 1_500 },
      { amount: 50, count: 6_500 },
      { amount: 30, count: 18_750 },
      { amount: 20, count: 37_500 },
      { amount: 10, count: 82_500 },
      { amount: 5, count: 577_500 },
    ],
    sourceUrl: HORSE_2026_RULES,
  },
  "horse-new-year": {
    groupSize: 1_800_000,
    prizeCounts: [
      { amount: 300_000, count: 1 },
      { amount: 10_000, count: 10 },
      { amount: 5_000, count: 20 },
      { amount: 1_000, count: 100 },
      { amount: 500, count: 400 },
      { amount: 200, count: 2_000 },
      { amount: 100, count: 7_500 },
      { amount: 50, count: 25_500 },
      { amount: 30, count: 37_500 },
      { amount: 20, count: 105_000 },
      { amount: 10, count: 525_000 },
    ],
    sourceUrl: HORSE_2026_RULES,
  },
  "horse-success-2026": {
    groupSize: 9_000_000,
    prizeCounts: [
      { amount: 1_000_000, count: 1 },
      { amount: 100_000, count: 10 },
      { amount: 10_000, count: 200 },
      { amount: 1_000, count: 1_500 },
      { amount: 500, count: 32_500 },
      { amount: 200, count: 15_000 },
      { amount: 100, count: 75_000 },
      { amount: 50, count: 375_000 },
      { amount: 30, count: 750_000 },
      { amount: 20, count: 2_175_000 },
    ],
    sourceUrl: HORSE_2026_RULES,
  },
  "head-start-2026": {
    groupSize: 9_000_000,
    prizeCounts: [
      { amount: 1_000_000, count: 1 },
      { amount: 500_000, count: 2 },
      { amount: 100_000, count: 10 },
      { amount: 10_000, count: 100 },
      { amount: 1_000, count: 3_000 },
      { amount: 800, count: 15_000 },
      { amount: 500, count: 38_000 },
      { amount: 200, count: 12_500 },
      { amount: 100, count: 225_000 },
      { amount: 50, count: 900_000 },
      { amount: 30, count: 2_250_000 },
    ],
    sourceUrl: HORSE_2026_RULES,
  },
  "new-year-luck-2026": {
    groupSize: 7_200_000,
    prizeCounts: [
      { amount: 1_000_000, count: 1 },
      { amount: 500_000, count: 4 },
      { amount: 100_000, count: 20 },
      { amount: 10_000, count: 160 },
      { amount: 1_000, count: 7_400 },
      { amount: 800, count: 36_000 },
      { amount: 500, count: 13_400 },
      { amount: 200, count: 90_000 },
      { amount: 150, count: 90_000 },
      { amount: 100, count: 630_000 },
      { amount: 50, count: 1_800_000 },
    ],
    sourceUrl: HORSE_2026_RULES,
  },
} satisfies Record<string, OfficialPrizeGroup>;

function bookSizeFor(price: number) {
  if (price === 10) return 50;
  if (price === 20) return 25;
  return 20;
}

function makePrizeTiers(price: number, topPrize: number, count: number): PrizeTier[] {
  const middle = [
    price,
    price * 2,
    price * 3,
    price * 5,
    100,
    200,
    500,
    1_000,
    5_000,
    10_000,
    50_000,
    100_000,
  ]
    .filter((amount, index, values) => amount < topPrize && values.indexOf(amount) === index)
    .slice(0, Math.max(1, count - 1));
  const weights = [42, 27, 18, 12, 7, 4, 2, 1, 0.35, 0.12, 0.03, 0.01];
  return [
    ...middle.map((amount, index) => ({ amount, weight: weights[index] ?? 0.01 })),
    { amount: topPrize, weight: 0.0004 },
  ];
}

function defaultJackpotBooks(price: number, topPrize: number) {
  const valueFactor = Math.max(0.55, Math.min(1.6, topPrize / 800_000));
  const priceFactor = 20 / price;
  return Math.round(48_000 * valueFactor * priceFactor);
}

function ticket(seed: TicketSeed): TicketType {
  const bookSize = seed.bookSize ?? bookSizeFor(seed.price);
  const publishedSmallWins = seed.publishedWinRate
    ? Math.round(bookSize * seed.publishedWinRate)
    : undefined;
  const distribution: TicketDistribution = {
    targetReturn: 0.65,
    smallWinsPerBook: publishedSmallWins
      ? [Math.max(1, publishedSmallWins - 2), publishedSmallWins + 2]
      : [Math.ceil(bookSize * 0.27), Math.ceil(bookSize * 0.4)],
    hundredEveryBooks:
      seed.price === 10 ? 4.2 : seed.price === 20 ? 3.6 : seed.price === 30 ? 3 : 1.15,
    jackpotEveryBooks: defaultJackpotBooks(seed.price, seed.topPrize),
    note: "65% 为发行层面资金比例；普通单本区间与大奖间隔是公开规则和实刮样本校准后的体验模型。",
    ...seed.distribution,
  };
  return {
    ...seed,
    bookSize,
    variantCount: seed.variantCount ?? 1,
    artSymbols: seed.artSymbols ?? ["福", "喜", "运", "彩"],
    prizeTiers: seed.officialPrizeGroup
      ? seed.officialPrizeGroup.prizeCounts.map(({ amount, count }) => ({
          amount,
          weight: count,
        }))
      : makePrizeTiers(seed.price, seed.topPrize, seed.prizeTierCount),
    distribution,
  };
}

export const TICKET_TYPES: TicketType[] = [
  ticket({
    id: "tenfold",
    name: "好运十倍",
    subtitle: "10元 · 经典数字对碰",
    issuer: "中国福利彩票",
    price: 10,
    opportunities: 10,
    prizeTierCount: 12,
    topPrize: 400_000,
    mode: "match",
    playFamily: "数字对比",
    mechanic: "任意“我的号码”与“中奖号码”相同即中同行奖金；出现“10”标志，奖金乘十。",
    design: "红金底、铜钱暗纹、中奖号码与十行对数字。",
    color: "#b72024",
    ink: "#fff3ca",
    accent: "#f2c14a",
    artSymbols: ["铜钱", "元宝", "十", "福"],
    variantCount: 4,
    evidence: "官方详规",
    sourceUrl: "https://www.gdfc.org.cn/datas/content/content_65032.html",
  }),
  ticket({
    id: "meeting-10",
    name: "喜相逢",
    subtitle: "10元 · 阿喜与囍",
    issuer: "中国福利彩票",
    price: 10,
    opportunities: 10,
    prizeTierCount: 11,
    topPrize: 300_000,
    mode: "symbol",
    playFamily: "找图符",
    mechanic: "刮出“阿喜”中下方奖金；刮出“囍”中下方奖金的两倍，奖金兼中兼得。",
    design: "朱红婚庆底、祥云与喜鹊、喜字奖符。",
    color: "#c4282d",
    ink: "#fff2d3",
    accent: "#f1c65d",
    artSymbols: ["喜鹊", "祥云", "阿喜", "囍"],
    variantCount: 4,
    evidence: "官方详规",
    sourceUrl: "https://www.hbfcw.cn/guagl/waggl/202208/t20220818_392396.shtml",
  }),
  ticket({
    id: "meeting-20",
    name: "喜相逢",
    subtitle: "20元 · 25次喜字寻奖",
    issuer: "中国福利彩票",
    price: 20,
    opportunities: 25,
    prizeTierCount: 10,
    topPrize: 800_000,
    mode: "symbol",
    playFamily: "找图符",
    mechanic: "刮出“阿喜”中下方奖金；刮出“囍”中下方奖金的两倍，奖金兼中兼得。",
    design: "红蓝双边、祥云仙鹤、满版祝福语与二十五格奖符。",
    color: "#194e83",
    ink: "#fff6dc",
    accent: "#e44035",
    artSymbols: ["仙鹤", "喜鹊", "阿喜", "囍"],
    variantCount: 4,
    evidence: "官方详规",
    sourceUrl: "https://www.hbfcw.cn/guagl/waggl/202208/t20220818_392396.shtml",
  }),
  ticket({
    id: "meeting-30",
    name: "喜相逢",
    subtitle: "30元 · 百万喜事",
    issuer: "中国福利彩票",
    price: 30,
    opportunities: 40,
    prizeTierCount: 12,
    topPrize: 1_000_000,
    mode: "symbol",
    playFamily: "找图符",
    mechanic: "刮出“阿喜”中下方奖金；刮出“囍”中下方奖金的两倍，奖金兼中兼得。",
    design: "大幅红金喜庆画面，鸳鸯、灯笼与双喜奖符。",
    color: "#9d1722",
    ink: "#fff0c2",
    accent: "#ffd065",
    artSymbols: ["鸳鸯", "灯笼", "阿喜", "囍"],
    variantCount: 4,
    evidence: "官方详规",
    sourceUrl: "https://www.hbfcw.cn/guagl/waggl/202208/t20220818_392396.shtml",
  }),
  ticket({
    id: "fortune",
    name: "好运来",
    subtitle: "30元 · 三玩法",
    issuer: "中国福利彩票",
    price: 30,
    opportunities: 18,
    prizeTierCount: 11,
    topPrize: 800_000,
    mode: "combo",
    playFamily: "组合玩法",
    mechanic: "三同图、图符即中和对数字三种玩法同在一张票上，三个区域奖金兼中兼得。",
    design: "红金锦鲤、福袋与金元宝，三块独立刮开区。",
    color: "#be2b20",
    ink: "#fff2ca",
    accent: "#f4c34e",
    artSymbols: ["锦鲤", "福袋", "元宝", "莲花"],
    variantCount: 2,
    evidence: "官方详规",
    sourceUrl: "https://www.gdfc.org.cn/datas/content/content_280922.html",
  }),
  ticket({
    id: "coast",
    name: "一路向海",
    subtitle: "10元 · 海南环岛主题",
    issuer: "中国体育彩票",
    price: 10,
    opportunities: 15,
    opportunityLabel: "主玩法 + 幸运玩法",
    prizeTierCount: 10,
    topPrize: 250_000,
    mode: "direct",
    playFamily: "金额即中",
    mechanic: "主玩法刮出奖金金额即中；幸运玩法刮出奖金标志即中。未中奖位置刮开后为空白。",
    design: "海岛公路、椰树与落日，共十五款沿线风景票面。",
    color: "#087c85",
    ink: "#fff8dc",
    accent: "#f3a24b",
    artSymbols: ["椰树", "海浪", "公路", "落日"],
    variantCount: 15,
    evidence: "官方介绍",
    sourceUrl: "https://www.sport.gov.cn/n20001280/n20067608/n20067637/c29014806/content.html",
  }),
  ticket({
    id: "many-joy-10",
    name: "多喜乐",
    subtitle: "10元 · 金额即开",
    issuer: "中国福利彩票",
    price: 10,
    opportunities: 15,
    prizeTierCount: 10,
    topPrize: 300_000,
    mode: "direct",
    playFamily: "金额即中",
    mechanic: "刮出任何奖金金额即中；刮出钱袋图符中100元，奖金兼中兼得。",
    design: "红黄蓝国潮配色，喜庆窗花、钱袋与欢乐人物。",
    color: "#d43b2f",
    ink: "#fff1b7",
    accent: "#2682a8",
    artSymbols: ["钱袋", "窗花", "彩带", "喜"],
    variantCount: 3,
    evidence: "官方详规",
    sourceUrl: "https://www.gdfc.org.cn/datas/content/content_275602.html",
  }),
  ticket({
    id: "many-joy-20",
    name: "多喜乐",
    subtitle: "20元 · 钱袋加奖",
    issuer: "中国福利彩票",
    price: 20,
    opportunities: 25,
    prizeTierCount: 10,
    topPrize: 800_000,
    mode: "direct",
    playFamily: "金额即中",
    mechanic: "刮出任何奖金金额即中；刮出钱袋图符中100元，奖金兼中兼得。",
    design: "红黄蓝国潮配色，大幅喜字、钱袋与层叠彩带。",
    color: "#b51e2b",
    ink: "#fff0bd",
    accent: "#1d6f9a",
    artSymbols: ["钱袋", "窗花", "彩带", "喜"],
    variantCount: 3,
    evidence: "官方详规",
    sourceUrl: "https://www.gdfc.org.cn/datas/content/content_275602.html",
  }),
  ...[
    [10, 300_000, 12, "match"],
    [20, 800_000, 20, "match"],
    [30, 1_000_000, 30, "combo"],
    [50, 1_000_000, 35, "combo"],
  ].map(([price, topPrize, opportunities, mode]) =>
    ticket({
      id: `many-fortune-${price}`,
      name: "福满多",
      subtitle: `${price}元 · 福气满格`,
      issuer: "中国福利彩票",
      price: price as number,
      opportunities: opportunities as number,
      prizeTierCount: price === 50 ? 9 : 10,
      topPrize: topPrize as number,
      mode: mode as PlayMode,
      playFamily: mode === "combo" ? "组合玩法" : "数字对比",
      mechanic: "对数字并寻找福袋特别图符；不同玩法区的奖金兼中兼得。",
      design: "红金福袋、团花、如意云纹与层叠福字。",
      color: price === 50 ? "#751924" : "#a9252d",
      ink: "#fff1c5",
      accent: "#efc052",
      artSymbols: ["福袋", "如意", "团花", "福"],
      variantCount: 4,
      evidence: "官方目录",
      sourceUrl: OFFICIAL_CATALOG,
    }),
  ),
  ...[
    [10, 300_000, 12, "symbol"],
    [20, 800_000, 20, "combo"],
    [30, 1_000_000, 30, "combo"],
    [50, 1_000_000, 35, "combo"],
  ].map(([price, topPrize, opportunities, mode]) =>
    ticket({
      id: `snake-${price}`,
      name: "乙巳蛇",
      subtitle: `${price}元 · 生肖贺岁`,
      issuer: "中国福利彩票",
      price: price as number,
      opportunities: opportunities as number,
      prizeTierCount: price === 10 ? 10 : 11,
      topPrize: topPrize as number,
      mode: mode as PlayMode,
      playFamily: mode === "symbol" ? "找图符" : "组合玩法",
      mechanic: "寻找生肖奖符，并在数字区域比对中奖号码；奖金兼中兼得。",
      design: "青金灵蛇、剪纸、如意纹与新春灯彩。",
      color: price === 50 ? "#143f3d" : "#1d6f61",
      ink: "#fff3ca",
      accent: "#e5b84c",
      artSymbols: ["灵蛇", "剪纸", "灯彩", "如意"],
      variantCount: 6,
      evidence: "官方目录",
      sourceUrl: OFFICIAL_CATALOG,
    }),
  ),
  ...[
    [10, 300_000, 12, 9, 0.32],
    [20, 800_000, 20, 10, 0.3764],
    [50, 1_000_000, 35, 8, 0.4125],
  ].map(([price, topPrize, opportunities, tiers, winRate]) =>
    ticket({
      id: `red-hot-${price}`,
      name: "正当红",
      subtitle: `${price}元 · 中国红`,
      issuer: "中国福利彩票",
      price: price as number,
      opportunities: opportunities as number,
      prizeTierCount: tiers as number,
      topPrize: topPrize as number,
      mode: "match",
      playFamily: "数字对比",
      mechanic: "数字对比配合特别图符，多个中奖位置可兼中兼得。",
      design: "大红底、中国结、灯笼与金色祝福纹样。",
      color: "#c31828",
      ink: "#fff1c9",
      accent: "#f5bd43",
      artSymbols: ["中国结", "灯笼", "烟花", "红"],
      variantCount: 3,
      evidence: "官方详规",
      sourceUrl: "https://www.hbfcw.cn/guagl/waggl/202110/t20211008_389526.shtml",
      publishedWinRate: winRate as number,
    }),
  ),
  ticket({
    id: "mountains",
    name: "三山五岳",
    subtitle: "20元 · 八座名山",
    issuer: "中国福利彩票",
    price: 20,
    opportunities: 20,
    prizeTierCount: 10,
    topPrize: 600_000,
    mode: "path",
    playFamily: "走步",
    mechanic: "按刮出的步数沿登山线路前进，停在奖金位置即中；各段奖金兼中兼得。",
    design: "庐山、黄山、雁荡山及五岳手绘风景，共八款票面。",
    color: "#275d4d",
    ink: "#f4efd8",
    accent: "#d79b43",
    artSymbols: ["山峰", "云海", "石阶", "松树"],
    variantCount: 8,
    evidence: "官方介绍",
    sourceUrl: "https://www.gdfc.org.cn/datas/content/content_271522.html",
  }),
  ticket({
    id: "golden-chest",
    name: "黄金宝箱",
    subtitle: "20元 · 像素冒险",
    issuer: "中国福利彩票",
    price: 20,
    opportunities: 20,
    prizeTierCount: 10,
    topPrize: 800_000,
    mode: "combo",
    playFamily: "组合玩法",
    mechanic: "玩法一金额即中；玩法二同一局刮出两个相同图符即中对应奖金。",
    design: "深蓝像素地牢、旋转金币与发光宝箱。",
    color: "#253873",
    ink: "#fff2ad",
    accent: "#f6bd2f",
    artSymbols: ["宝箱", "金币", "钥匙", "钻石"],
    variantCount: 2,
    evidence: "官方详规",
    sourceUrl: "https://www.gdfc.org.cn/datas/content/content_269322.html",
  }),
  ticket({
    id: "panda-dream",
    name: "追梦攀达",
    subtitle: "20元 · 熊猫攀登",
    issuer: "中国福利彩票",
    price: 20,
    opportunities: 24,
    prizeTierCount: 10,
    topPrize: 1_000_000,
    mode: "path",
    playFamily: "走步",
    mechanic: "根据刮出的步数沿攀登路线移动，抵达奖位即中；特别图符触发对应奖金。",
    design: "熊猫、竹林、雪山与户外攀登路线。",
    color: "#346b53",
    ink: "#f7f2dc",
    accent: "#d6a33e",
    artSymbols: ["熊猫", "竹叶", "雪山", "绳索"],
    variantCount: 4,
    evidence: "官方目录",
    sourceUrl: OFFICIAL_CATALOG,
  }),
  ticket({
    id: "triple-six",
    name: "666",
    subtitle: "10元 · 三同数字",
    issuer: "中国福利彩票",
    price: 10,
    opportunities: 12,
    prizeTierCount: 10,
    topPrize: 600_000,
    mode: "triple",
    playFamily: "三同图",
    mechanic: "同一局出现三个相同数字或图符，即中该局对应奖金。",
    design: "紫金霓虹数字6、钻石切面与光束。",
    color: "#623a8c",
    ink: "#fff0c9",
    accent: "#f1c84a",
    artSymbols: ["6", "钻石", "星", "皇冠"],
    variantCount: 3,
    evidence: "官方目录",
    sourceUrl: OFFICIAL_CATALOG,
  }),
  ticket({
    id: "double-happiness",
    name: "囍",
    subtitle: "20元 · 四款喜礼",
    issuer: "中国福利彩票",
    price: 20,
    opportunities: 25,
    prizeTierCount: 10,
    topPrize: 1_000_000,
    mode: "direct",
    playFamily: "金额即中",
    mechanic: "刮出任何奖金金额即中，中奖奖金兼中兼得。",
    design: "龙凤呈祥、永结同心、丰衣足食、称心如意四款红金票面。",
    color: "#ae1e2c",
    ink: "#fff0cd",
    accent: "#efbd4e",
    artSymbols: ["龙凤", "同心结", "如意", "囍"],
    variantCount: 4,
    evidence: "官方详规",
    sourceUrl: "https://www.gdfc.org.cn/datas/content/content_265892.html",
  }),
  ticket({
    id: "starlight",
    name: "星光灿烂",
    subtitle: "30元 · 30局星光",
    issuer: "中国福利彩票",
    price: 30,
    opportunities: 30,
    prizeTierCount: 11,
    topPrize: 1_000_000,
    mode: "match",
    playFamily: "数字对比",
    mechanic: "同局“我的号码”与“中奖号码”相同即中右侧奖金；星星图符同样中奖。",
    design: "深邃夜空、鎏金星星与钻石光影，两款票面。",
    color: "#1c285f",
    ink: "#fff4c6",
    accent: "#e8c85b",
    artSymbols: ["星星", "钻石", "星云", "月光"],
    variantCount: 2,
    evidence: "官方详规",
    sourceUrl: "https://www.gdfc.org.cn/datas/content/content_282992.html?subjectID=43",
  }),
  ticket({
    id: "prosperous-china",
    name: "盛世中华",
    subtitle: "50元 · 百万大票",
    issuer: "中国福利彩票",
    price: 50,
    opportunities: 35,
    prizeTierCount: 9,
    topPrize: 1_000_000,
    mode: "combo",
    playFamily: "组合玩法",
    mechanic: "多区数字对比与特别图符组合，奖金兼中兼得。",
    design: "鲜红底、金色线描传统纹饰与大字标题。",
    color: "#8d1823",
    ink: "#fff0c2",
    accent: "#f0bf4a",
    artSymbols: ["华表", "山河", "金纹", "中华"],
    variantCount: 1,
    evidence: "官方介绍",
    sourceUrl: "https://www.gdfc.org.cn/datas/content/content_271062.html",
  }),
  ticket({
    id: "big-winner",
    name: "大赢家",
    subtitle: "10元 · 通吃号码",
    issuer: "中国福利彩票",
    price: 10,
    opportunities: 19,
    prizeTierCount: 10,
    topPrize: 250_000,
    mode: "combo",
    playFamily: "组合玩法",
    mechanic: "玩法一金额即中；玩法二号码比对，命中“通吃号码”可得该区全部奖金之和。",
    design: "紫金底、王冠、飘带、五角星盾牌与立体标题。",
    color: "#5c318a",
    ink: "#fff2bf",
    accent: "#e4b33e",
    artSymbols: ["王冠", "盾牌", "星", "奖杯"],
    variantCount: 2,
    evidence: "官方详规",
    sourceUrl: "https://www.gdfc.org.cn/datas/content/content_256842.html",
  }),
  ticket({
    id: "dream-football",
    name: "梦寐以求",
    subtitle: "20元 · 足球主题",
    issuer: "中国福利彩票",
    price: 20,
    opportunities: 30,
    prizeTierCount: 11,
    topPrize: 1_000_000,
    mode: "compare",
    playFamily: "比大小",
    mechanic: "即中区与对数字区组合；竞技局中自己的分数高于对手即可获得对应奖金。",
    design: "绿茵球场、球衣、足球与赛事记分牌。",
    color: "#126347",
    ink: "#f5f1d5",
    accent: "#f0ba42",
    artSymbols: ["足球", "球衣", "球门", "奖杯"],
    variantCount: 4,
    evidence: "官方详规",
    sourceUrl: "https://www.hbfcw.cn/guagl/waggl/202211/t20221117_393270.shtml",
  }),
  ticket({
    id: "seven-joy",
    name: "7乐无穷",
    subtitle: "10元 · 三同7",
    issuer: "中国福利彩票",
    price: 10,
    opportunities: 16,
    prizeTierCount: 9,
    topPrize: 250_000,
    mode: "triple",
    playFamily: "三同图",
    mechanic: "同一局刮出三个相同图符，即中该局后方奖金。",
    design: "红、蓝、绿三款钻石光效票面，数字7为主视觉。",
    color: "#135a79",
    ink: "#fff3cd",
    accent: "#e93f58",
    artSymbols: ["7", "钻石", "星光", "彩球"],
    variantCount: 3,
    evidence: "官方介绍",
    sourceUrl: "https://www.gdfc.org.cn/datas/content/content_283382.html?subjectID=43",
  }),
  ticket({
    id: "luxury-seven",
    name: "壕7",
    subtitle: "10元 · 七倍惊喜",
    issuer: "中国福利彩票",
    price: 10,
    opportunities: 15,
    prizeTierCount: 9,
    topPrize: 400_000,
    mode: "combo",
    playFamily: "组合玩法",
    mechanic: "数字比对与三同图组合；特别“7”图符可令对应奖金翻七倍。",
    design: "土豪金底、大号数字7与黑金几何切面。",
    color: "#9a7123",
    ink: "#fff3cb",
    accent: "#28231c",
    artSymbols: ["7", "金砖", "钻石", "皇冠"],
    variantCount: 2,
    evidence: "官方详规",
    sourceUrl: "https://www.hbfcw.cn/hidden/201808/t20180830_371435.shtml",
  }),
  ticket({
    id: "star-shine",
    name: "星光闪耀",
    subtitle: "20元 · 找标志与通吃",
    issuer: "中国体育彩票",
    price: 20,
    opportunities: 20,
    prizeTierCount: 9,
    topPrize: 1_000_000,
    mode: "symbol",
    playFamily: "找图符",
    mechanic: "出现顶呱刮标志中下方奖金；出现星星标志中刮开区全部金额之和。",
    design: "紫、蓝、黑三款夜空票面，以星星和光束为主视觉。",
    color: "#29346f",
    ink: "#fff1c3",
    accent: "#e4c44c",
    artSymbols: ["星星", "光束", "体彩", "星云"],
    variantCount: 3,
    evidence: "官方详规",
    sourceUrl: "https://www.sport.gov.cn/n20001280/n20745751/n20767297/c21137576/content.html",
    publishedWinRate: 0.34,
  }),
  ticket({
    id: "sesame-rise",
    name: "芝麻开花节节高",
    subtitle: "10元 · 步步向上",
    issuer: "中国体育彩票",
    price: 10,
    opportunities: 15,
    prizeTierCount: 10,
    topPrize: 300_000,
    mode: "path",
    playFamily: "走步",
    mechanic: "按刮出的步数沿节节高路线移动，停在奖金位置即中。",
    design: "青绿芝麻花、层层台阶与向上生长的金色轨迹。",
    color: "#397443",
    ink: "#fff4d4",
    accent: "#e9b941",
    artSymbols: ["芝麻花", "台阶", "叶片", "阳光"],
    variantCount: 3,
    evidence: "官方介绍",
    sourceUrl: "https://www.sport.gov.cn/n20001280/n20745751/n20767297/c21137576/content.html",
  }),
  ticket({
    id: "cash-20x",
    name: "20倍现金",
    subtitle: "20元 · 倍数现金",
    issuer: "中国体育彩票",
    price: 20,
    opportunities: 20,
    prizeTierCount: 10,
    topPrize: 1_000_000,
    mode: "match",
    playFamily: "数字对比",
    mechanic: "号码相同即中对应奖金；特别倍数标志令该位置奖金按倍数计算。",
    design: "银墨现金纹理、醒目20X字样与绿色钞票元素。",
    color: "#315f49",
    ink: "#f6f3dc",
    accent: "#c9cdd0",
    artSymbols: ["20X", "现金", "银墨", "星"],
    variantCount: 2,
    evidence: "官方介绍",
    sourceUrl: "https://www.sport.gov.cn/n20001280/n20745751/n20767239/c21682626/content.html",
  }),
  ticket({
    id: "world-diamond",
    name: "天下名钻",
    subtitle: "10元 · 钻石寻奖",
    issuer: "中国体育彩票",
    price: 10,
    opportunities: 15,
    prizeTierCount: 10,
    topPrize: 500_000,
    mode: "symbol",
    playFamily: "找图符",
    mechanic: "寻找指定钻石奖符与通吃图符，奖金兼中兼得。",
    design: "深蓝天鹅绒底、钻石切面与冷白高光。",
    color: "#1d335d",
    ink: "#f8f3dc",
    accent: "#b8d6e8",
    artSymbols: ["钻石", "戒指", "皇冠", "星芒"],
    variantCount: 4,
    evidence: "官方介绍",
    sourceUrl: "https://www.sport.gov.cn/n20001280/n20745751/n20767239/c21682626/content.html",
  }),
  ticket({
    id: "gold-jade",
    name: "金玉满堂",
    subtitle: "30元 · 变色墨玉石",
    issuer: "中国体育彩票",
    price: 30,
    opportunities: 30,
    prizeTierCount: 11,
    topPrize: 1_000_000,
    mode: "combo",
    playFamily: "组合玩法",
    mechanic: "数字对比与特别图符组合，奖金兼中兼得。",
    design: "深棕底、翠绿玉石与金砖，采用变色墨视觉效果。",
    color: "#4a3627",
    ink: "#f6efd5",
    accent: "#49a879",
    artSymbols: ["玉石", "金砖", "如意", "宝珠"],
    variantCount: 2,
    evidence: "官方介绍",
    sourceUrl: "https://www.sport.gov.cn/n20001280/n20745751/n20767297/c21217114/content.html",
  }),
  ticket({
    id: "step-up",
    name: "步步登高",
    subtitle: "10元 · 新年登高",
    issuer: "中国体育彩票",
    price: 10,
    opportunities: 15,
    prizeTierCount: 10,
    topPrize: 300_000,
    mode: "path",
    playFamily: "走步",
    mechanic: "按步数沿登高线路移动，抵达奖金位置即中。",
    design: "清雅山色、石阶、松树与登高远眺的人物。",
    color: "#54735d",
    ink: "#f6f0dc",
    accent: "#d7a34a",
    artSymbols: ["山峰", "石阶", "松树", "云海"],
    variantCount: 3,
    evidence: "官方介绍",
    sourceUrl: "https://www.sport.gov.cn/n20001280/n20067608/n20067637/c29358756/content.html",
  }),
  ticket({
    id: "snow-dragon",
    name: "雪舞龙腾",
    subtitle: "20元 · 冰雪竞技",
    issuer: "中国体育彩票",
    price: 20,
    opportunities: 20,
    prizeTierCount: 10,
    topPrize: 800_000,
    mode: "compare",
    playFamily: "比大小",
    mechanic: "同局比赛成绩优于对手即中对应奖金；特别龙腾图符直接中奖。",
    design: "冰蓝雪道、腾龙、滑雪剪影与冬奥色彩。",
    color: "#2e6f9c",
    ink: "#f6f7ef",
    accent: "#e24f3f",
    artSymbols: ["雪花", "腾龙", "滑雪", "奖牌"],
    variantCount: 4,
    evidence: "官方介绍",
    sourceUrl: "https://www.sport.gov.cn/n20001280/n20067608/n20067637/c29358756/content.html",
  }),
  ticket({
    id: "long-march",
    name: "长征",
    subtitle: "10元 · 五幅历史场景",
    issuer: "中国体育彩票",
    price: 10,
    opportunities: 12,
    prizeTierCount: 10,
    topPrize: 300_000,
    mode: "path",
    playFamily: "走步",
    mechanic: "按线路刮开历史节点并寻找中奖图符，奖金兼中兼得。",
    design: "遵义会议、飞夺泸定桥、雪山、会师与军民情深五款场景。",
    color: "#a42b27",
    ink: "#f7eccf",
    accent: "#d9b04a",
    artSymbols: ["路线图", "桥", "雪山", "会师"],
    variantCount: 5,
    evidence: "官方详规",
    sourceUrl: "https://www.sport.gov.cn/n20001280/n20745751/n20767297/c21188558/content.html",
  }),
  ticket({
    id: "lucky-6688",
    name: "66顺88发",
    subtitle: "10元 · 66/88与六八倍奖",
    issuer: "中国福利彩票",
    price: 10,
    opportunities: 12,
    prizeTierCount: 11,
    topPrize: 250_000,
    mode: "symbol",
    playFamily: "找图符",
    mechanic: "刮出“66”或“88”得下方奖金；刮出“顺”得6倍奖金；刮出“发”得8倍奖金，兼中兼得。",
    design: "黑色底板配彩色6与8、星芒和十二个横向奖格，玩法字样占据票面上半部。",
    color: "#171719",
    ink: "#fff5d8",
    accent: "#f04f36",
    artSymbols: ["66", "88", "顺", "发"],
    winningSymbols: [
      { label: "66", multiplier: 1 },
      { label: "88", multiplier: 1 },
      { label: "顺", multiplier: 6 },
      { label: "发", multiplier: 8 },
    ],
    variantCount: 2,
    distribution: {
      hundredEveryBooks: 5,
      jackpotEveryBooks: 85_000,
    },
    evidence: "官方详规",
    sourceUrl: "https://www.yzfcw.com/game/gglNewsContent?classficationId=82&newsId=17815",
  }),
  ticket({
    id: "three-yuan",
    name: "连中三元",
    subtitle: "30元 · 二十四局三元宝",
    issuer: "中国福利彩票",
    price: 30,
    opportunities: 24,
    opportunityLabel: "24局 · 每局3个图符",
    prizeTierCount: 9,
    topPrize: 1_000_000,
    mode: "triple",
    playFamily: "三同图",
    mechanic: "同一局刮出3个元宝图符，即中该局右侧奖金；24局奖金兼中兼得。",
    design: "墨绿色竖版票面、暗红边框、两列十二行局号，从中心向外放射金色光影。",
    color: "#17483a",
    ink: "#f7e8b7",
    accent: "#b23c32",
    artSymbols: ["元宝", "祥云", "灯笼", "锦鲤"],
    variantCount: 1,
    distribution: {
      hundredEveryBooks: 4.6,
      jackpotEveryBooks: 110_000,
    },
    evidence: "官方介绍",
    sourceUrl: "https://www.zhcw.com/c/2022-06-24/786218.shtml",
  }),
  ticket({
    id: "tang-song",
    name: "唐风宋韵",
    subtitle: "30元 · 六枚古画套票",
    issuer: "中国福利彩票",
    price: 30,
    opportunities: 36,
    prizeTierCount: 9,
    topPrize: 1_000_000,
    mode: "match",
    playFamily: "数字对比",
    mechanic: "刮开各局，将我的号码与中奖号码比对；相同即中该局奖金，奖金兼中兼得。",
    design: "六款唐宋名画主题，宣纸米色留白、绛红印章与现代网格排版相结合。",
    color: "#76533e",
    ink: "#fff2d7",
    accent: "#b5362f",
    artSymbols: ["祥云", "山峰", "锦鲤", "灯笼"],
    variantCount: 6,
    evidence: "官方介绍",
    sourceUrl: "https://www.qlfc.com.cn/system/2024/05/07/030018894.shtml",
  }),
  ticket({
    id: "fortune-cat",
    name: "招财猫",
    subtitle: "20元 · 二十次招财机会",
    issuer: "中国福利彩票",
    price: 20,
    opportunities: 20,
    prizeTierCount: 10,
    topPrize: 500_000,
    mode: "symbol",
    playFamily: "找图符",
    mechanic: "在二十个玩法位置寻找招财奖符，刮出奖符即中下方对应奖金。",
    design: "红金招财猫、金铃、金币与日式青海波纹，票面中心为二十格玩法区。",
    color: "#b72b25",
    ink: "#fff0c2",
    accent: "#edbd49",
    artSymbols: ["钱袋", "元宝", "锦鲤", "皇冠"],
    variantCount: 3,
    evidence: "官方介绍",
    sourceUrl: "https://www.zhcw.com/c/2024-12-06/875679.shtml",
  }),
  ticket({
    id: "peaceful-harvest",
    name: "国泰民安",
    subtitle: "10元 · 五谷丰登三玩法",
    issuer: "中国福利彩票",
    price: 10,
    opportunities: 15,
    prizeTierCount: 10,
    topPrize: 300_000,
    mode: "combo",
    playFamily: "组合玩法",
    mechanic: "玩法一寻找中奖图符；玩法二刮出3个相同金额即中；玩法三刮出特别图符中50元。",
    design: "中国红底、华表、稻谷、灯笼与礼花，三块玩法区用金线分隔。",
    color: "#b61e25",
    ink: "#fff0c6",
    accent: "#e5bd50",
    artSymbols: ["灯笼", "中国结", "祥云", "元宝"],
    variantCount: 1,
    evidence: "官方详规",
    sourceUrl: "https://mzj.gz.gov.cn/gzfcw/csxw/content/post_10256431.html",
  }),
  ...[
    ["flowers", "繁花似锦", "#a92f4c", ["锦鲤", "祥云", "元宝", "喜鹊"]],
    ["safe-road", "一路平安", "#284f58", ["祥云", "山峰", "竹叶", "喜鹊"]],
    ["success", "马到成功", "#984020", ["山峰", "祥云", "皇冠", "奖杯"]],
    ["happy-brow", "喜上眉梢", "#a91f31", ["喜鹊", "祥云", "灯笼", "中国结"]],
  ].map(([id, subtitle, color, symbols]) =>
    ticket({
      id: `blessed-${id}`,
      name: "有福",
      subtitle: `20元 · ${subtitle}`,
      issuer: "中国福利彩票",
      price: 20,
      opportunities: 20,
      prizeTierCount: 10,
      topPrize: 1_000_000,
      mode: "combo",
      playFamily: "组合玩法",
      mechanic: "图符、三同图与数字比对组合玩法分区呈现，各区奖金兼中兼得。",
      design: `${subtitle}国潮主题，传统吉祥物与花卉纹样围绕中央玩法区。`,
      color: color as string,
      ink: "#fff2ce",
      accent: "#e2b64d",
      artSymbols: symbols as string[],
      variantCount: 1,
      evidence: "官方介绍",
      sourceUrl: "https://www.zhcw.com/c/2025-05-30/891847.shtml",
    }),
  ),
  ticket({
    id: "rainbow-gems",
    name: "彩虹宝石",
    subtitle: "20元 · 宝石图符即中",
    issuer: "中国福利彩票",
    price: 20,
    opportunities: 20,
    prizeTierCount: 10,
    topPrize: 1_000_000,
    mode: "symbol",
    playFamily: "找图符",
    mechanic: "刮出宝石图符，即可获得该图符下方所对应的奖金，奖金兼中兼得。",
    design: "紫蓝渐变底、切割宝石、彩虹折射光和二十格纵向玩法区。",
    color: "#553a89",
    ink: "#fff3dd",
    accent: "#e75e91",
    artSymbols: ["宝石", "钻石", "皇冠", "星芒"],
    variantCount: 3,
    evidence: "官方详规",
    sourceUrl: "https://www.gdfc.org.cn/datas/content/content_272992.html?subjectID=43",
  }),
  ticket({
    id: "tang-tide",
    name: "唐潮",
    subtitle: "20元 · 金额即中",
    issuer: "中国福利彩票",
    price: 20,
    opportunities: 20,
    prizeTierCount: 10,
    topPrize: 1_000_000,
    mode: "direct",
    playFamily: "金额即中",
    mechanic: "玩法区刮出任何奖金金额即中得该奖金，所有中奖金额兼中兼得。",
    design: "唐代仪仗、彩绘散乐和阙楼纹样，朱砂、石青与鎏金配色。",
    color: "#7f342c",
    ink: "#f5e8c8",
    accent: "#d9a643",
    artSymbols: ["灯笼", "祥云", "山峰", "元宝"],
    variantCount: 5,
    evidence: "官方介绍",
    sourceUrl: "https://www.news.cn/caipiao/20220609/c09bd80d1d454aff86d10497e23bf780/c.html",
  }),
  ticket({
    id: "lucky-123",
    name: "幸运123",
    subtitle: "20元 · 图符/金额/号码三玩法",
    issuer: "中国福利彩票",
    price: 20,
    opportunities: 19,
    opportunityLabel: "19次 · 三块独立玩法区",
    prizeTierCount: 10,
    topPrize: 1_000_000,
    mode: "combo",
    playFamily: "组合玩法",
    mechanic: "玩法一同局三同图；玩法二刮出奖金金额即中；玩法三“我的号码”与“中奖号码”相同即中，三区奖金兼中兼得。",
    design: "红蓝两款立体数字1/2/3主视觉，礼盒、心形与彩带围绕三块刮开区。",
    color: "#204a8b",
    ink: "#fff2d4",
    accent: "#ec4f43",
    artSymbols: ["礼盒", "爱心", "星星", "金币"],
    variantCount: 2,
    evidence: "官方详规",
    sourceUrl: "https://www.yzfcw.com/history/newsContent?newsId=18983",
  }),
  ticket({
    id: "opera-show",
    name: "非常有戏",
    subtitle: "10元 · 生旦净丑国潮票",
    issuer: "中国福利彩票",
    price: 10,
    opportunities: 8,
    prizeTierCount: 8,
    topPrize: 100_000,
    mode: "symbol",
    playFamily: "找图符",
    mechanic: "刮出书法“戏”奖符，即中该图符右侧对应奖金；折扇、二胡、锣鼓和脸谱均为非中奖图符。",
    design: "四张生旦净丑手绘戏曲套票，红蓝撞色、脸谱、折扇与舞台幕布。",
    color: "#8d263a",
    ink: "#f8ecd2",
    accent: "#2d7c8f",
    artSymbols: ["折扇", "二胡", "锣鼓", "脸谱"],
    winningSymbols: [{ label: "戏", multiplier: 1 }],
    variantCount: 4,
    publishedWinRate: 0.3408,
    evidence: "官方详规",
    sourceUrl: "https://www.yzfcw.com/game/ssqNewsContent?newsId=18948",
  }),
  ticket({
    id: "mushroom-hunt",
    name: "采蘑菇",
    subtitle: "5元 · 蘑菇即中与篮子通吃",
    issuer: "中国体育彩票",
    price: 5,
    bookSize: 100,
    opportunities: 8,
    prizeTierCount: 11,
    topPrize: 100_000,
    mode: "symbol",
    playFamily: "找图符",
    mechanic: "刮出蘑菇图符得下方奖金；刮出篮子图符，获得刮开区8个金额之和，奖金兼中兼得。",
    design: "红色蘑菇、草叶与藤蔓构成童话森林，八个奖位排成采集路径。",
    color: "#b72c29",
    ink: "#fff0d0",
    accent: "#5f8f43",
    artSymbols: ["蘑菇", "花朵", "竹叶", "篮子"],
    winningSymbols: [
      { label: "蘑菇", multiplier: 1 },
      { label: "篮子", multiplier: 1, award: "all" },
    ],
    variantCount: 1,
    evidence: "官方详规",
    sourceUrl: "https://www.sport.gov.cn/n20001280/n20745751/n20767297/c21223190/content.html",
  }),
  ticket({
    id: "best-wishes",
    name: "万事如意",
    subtitle: "20元 · 灯笼与如意翻倍",
    issuer: "中国福利彩票",
    price: 20,
    opportunities: 20,
    prizeTierCount: 10,
    topPrize: 1_000_000,
    mode: "symbol",
    playFamily: "找图符",
    mechanic: "刮出灯笼图符得下方奖金；刮出如意图符得下方奖金两倍，奖金兼中兼得。",
    design: "走财运、降祥瑞、添如意、旺桃花、涨福气、升职级六款传统纹样票面。",
    color: "#b1272d",
    ink: "#fff1d0",
    accent: "#d9ad45",
    artSymbols: ["灯笼", "如意", "莲花", "祥云"],
    winningSymbols: [
      { label: "灯笼", multiplier: 1 },
      { label: "如意", multiplier: 2 },
    ],
    variantCount: 6,
    evidence: "官方介绍",
    sourceUrl: "https://www.gdfc.org.cn/datas/content/content_282152.html?subjectID=13",
  }),
  ticket({
    id: "sprout",
    name: "新芽",
    subtitle: "10元 · 八边形可折叠票",
    issuer: "中国福利彩票",
    price: 10,
    opportunities: 12,
    opportunityLabel: "数字/金额/三同图组合区",
    prizeTierCount: 8,
    topPrize: 100_000,
    mode: "combo",
    playFamily: "组合玩法",
    mechanic: "数字匹配、奖金金额即中与三同图三种玩法分区呈现，中奖奖金兼中兼得。",
    design: "黄绿与红色两款八边形异形票，叶片、树苗与折叠压线可组成小盒。",
    color: "#5b8738",
    ink: "#f6f1cc",
    accent: "#e3b43e",
    artSymbols: ["新芽", "竹叶", "花朵", "阳光"],
    variantCount: 2,
    evidence: "官方介绍",
    sourceUrl: "https://www.zhcw.com/c/2019-06-06/574190.shtml",
  }),
  ticket({
    id: "wu-horse",
    name: "午马",
    subtitle: "5元 · 九联剪纸贺岁票",
    issuer: "中国体育彩票",
    price: 5,
    bookSize: 100,
    opportunities: 8,
    opportunityLabel: "金额即中 · 九联收藏票",
    prizeTierCount: 11,
    topPrize: 100_000,
    mode: "direct",
    playFamily: "金额即中",
    mechanic: "玩法区出现奖金金额即中，中奖奖金兼中兼得。",
    design: "九张可拼成骏马剪纸窗花的红金联票，每张带不同马年祝福语。",
    color: "#b51f26",
    ink: "#fff1c9",
    accent: "#e5b441",
    artSymbols: ["骏马", "窗花", "祥云", "灯笼"],
    variantCount: 9,
    officialPrizeGroup: HORSE_2026_PRIZE_GROUPS["wu-horse"],
    publishedWinRate: 724_906 / 1_800_000,
    evidence: "官方详规",
    sourceUrl: HORSE_2026_RULES,
  }),
  ticket({
    id: "horse-new-year",
    name: "骏马贺岁",
    subtitle: "10元 · 两同骏马与灯笼三倍",
    issuer: "中国体育彩票",
    price: 10,
    opportunities: 12,
    prizeTierCount: 11,
    topPrize: 300_000,
    mode: "pairs",
    playFamily: "两同图",
    mechanic: "任意一局出现两个相同骏马图符即中右侧奖金；出现灯笼图符即中该局奖金三倍，奖金兼中兼得。",
    design: "黑、白、紫、赤四色名驹，马身饰牡丹、如意、蝙蝠与莲花吉祥纹。",
    color: "#762e38",
    ink: "#fff0cc",
    accent: "#e1b24c",
    artSymbols: ["骏马", "灯笼", "牡丹", "莲花"],
    pairRule: {
      matchLabel: "骏马",
      bonusLabel: "灯笼",
      bonusMultiplier: 3,
    },
    variantCount: 4,
    officialPrizeGroup: HORSE_2026_PRIZE_GROUPS["horse-new-year"],
    publishedWinRate: 703_031 / 1_800_000,
    evidence: "官方详规",
    sourceUrl: HORSE_2026_RULES,
  }),
  ticket({
    id: "horse-success-2026",
    name: "马到成功",
    subtitle: "20元 · 骏马/祥云/成功通吃",
    issuer: "中国体育彩票",
    price: 20,
    opportunities: 25,
    prizeTierCount: 10,
    topPrize: 1_000_000,
    mode: "symbol",
    playFamily: "找图符",
    mechanic: "刮出骏马图符得下方奖金；祥云图符得两倍；成功图符获得刮开区25个金额之和。",
    design: "红橘蓝三款现代装饰版画，骏马头戴唐代仪仗风格当卢。",
    color: "#bd4930",
    ink: "#fff1d3",
    accent: "#284f84",
    artSymbols: ["骏马", "祥云", "成功", "奖牌"],
    winningSymbols: [
      { label: "骏马", multiplier: 1 },
      { label: "祥云", multiplier: 2 },
      { label: "成功", multiplier: 1, award: "all" },
    ],
    variantCount: 3,
    officialPrizeGroup: HORSE_2026_PRIZE_GROUPS["horse-success-2026"],
    publishedWinRate: 3_424_211 / 9_000_000,
    evidence: "官方详规",
    sourceUrl: HORSE_2026_RULES,
  }),
  ticket({
    id: "head-start-2026",
    name: "抢头彩2026",
    subtitle: "30元 · 金额即中与头彩两倍",
    issuer: "中国体育彩票",
    price: 30,
    opportunities: 24,
    opportunityLabel: "金额区 + 号码区",
    prizeTierCount: 11,
    topPrize: 1_000_000,
    mode: "combo",
    playFamily: "组合玩法",
    mechanic: "玩法一刮出奖金金额即中；玩法二号码匹配即中，出现头彩图符得下方奖金两倍。",
    design: "两款复古国潮骏马插画，鲜明撞色、头彩旗帜与奔腾动势。",
    color: "#224f89",
    ink: "#fff0d0",
    accent: "#ef5d3f",
    artSymbols: ["骏马", "旗帜", "祥云", "奖杯"],
    variantCount: 2,
    officialPrizeGroup: HORSE_2026_PRIZE_GROUPS["head-start-2026"],
    publishedWinRate: 3_443_613 / 9_000_000,
    evidence: "官方详规",
    sourceUrl: HORSE_2026_RULES,
  }),
  ticket({
    id: "new-year-luck-2026",
    name: "新春大吉2026",
    subtitle: "50元 · 背面大刮区收藏票",
    issuer: "中国体育彩票",
    price: 50,
    opportunities: 40,
    opportunityLabel: "金额区 + 号码/倍数区",
    prizeTierCount: 11,
    topPrize: 1_000_000,
    mode: "combo",
    playFamily: "组合玩法",
    mechanic: "玩法一刮出奖金金额即中；玩法二号码匹配即中，骏马图符得两倍，大吉图符得五倍。",
    design: "横版中国红，八匹奔马、金色祥云与火红灯笼；刮开区设置在票背。",
    color: "#a91f25",
    ink: "#fff0c7",
    accent: "#d9aa3f",
    artSymbols: ["骏马", "祥云", "灯笼", "大吉"],
    variantCount: 1,
    officialPrizeGroup: HORSE_2026_PRIZE_GROUPS["new-year-luck-2026"],
    publishedWinRate: 2_666_985 / 7_200_000,
    evidence: "官方详规",
    sourceUrl: HORSE_2026_RULES,
  }),
  ticket({
    id: "super-nine",
    name: "超级9",
    subtitle: "50元 · 九宫组合玩法",
    issuer: "中国福利彩票",
    price: 50,
    opportunities: 40,
    prizeTierCount: 11,
    topPrize: 1_000_000,
    mode: "combo",
    playFamily: "组合玩法",
    mechanic: "多个数字与图符玩法集中在一张大票上，特别“9”图符触发对应奖金。",
    design: "黑金大幅票面、立体数字9、九宫纹理与密集的分区刮开面。",
    color: "#252126",
    ink: "#fff0bf",
    accent: "#d8a83e",
    artSymbols: ["皇冠", "钻石", "星芒", "元宝"],
    variantCount: 2,
    distribution: {
      hundredEveryBooks: 1.35,
      jackpotEveryBooks: 90_000,
    },
    evidence: "官方介绍",
    sourceUrl: "https://www.hbfcw.cn/guagl/waggl/202605/t20260514_405309.shtml",
  }),
];

export const CATALOG_SIZE = TICKET_TYPES.length;
